
package student_managment;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Minea
 */
public class Confirm extends javax.swing.JFrame {

    /**
     * Creates new form Confirm
     */
    public Confirm() {
        initComponents();
        SetIcons objs = new SetIcons();
        objs.SetIcons(this);
        lbl_msg.setVisible(false);
        txtcode.requestFocus();
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    String sql;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcode = new javax.swing.JTextField();
        btnconfrim = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_msg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Confirmation Code");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Digital Code");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 126, -1, -1));

        txtcode.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        txtcode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodeKeyTyped(evt);
            }
        });
        jPanel1.add(txtcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 120, 218, 32));

        btnconfrim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnconfrim.setText("Confirm");
        btnconfrim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfrimActionPerformed(evt);
            }
        });
        jPanel1.add(btnconfrim, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 183, 80, 32));

        btnclose.setBackground(new java.awt.Color(255, 255, 255));
        btnclose.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnclose.setForeground(new java.awt.Color(255, 0, 51));
        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 183, 80, 32));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Please go to open your email account and complete code here,");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 71, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 153));
        jLabel4.setText("6 Digits");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 92, 59, -1));

        lbl_msg.setForeground(new java.awt.Color(255, 0, 0));
        lbl_msg.setText("Incorrect code");
        jPanel1.add(lbl_msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 158, 79, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodeKeyTyped
        char c=evt.getKeyChar();
        if (Character.isLetter(c) && ! evt.isAltDown() || Character.isSpaceChar(c) || ! Character.isDigit(c)) {
            evt.consume();
        }else{
            if(txtcode.getText().trim().length() >= 6){
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtcodeKeyTyped

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnconfrimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfrimActionPerformed
        if(txtcode.getText().isEmpty()){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Please input Digital code","Message",JOptionPane.WARNING_MESSAGE);
            txtcode.requestFocus();
        }else{
            con=ConDB.getConnection();
            int conCode = Integer.parseInt(txtcode.getText().trim());
            try {
                    sql="Select digital_code from tbl_forgot_pass where digital_code="+conCode+"";
                    pst=con.prepareStatement(sql);
                    rs=pst.executeQuery();
                    
                    if(rs.next()){
                        lbl_msg.setVisible(false);
                        sql="DELETE from tbl_forgot_pass where digital_code="+conCode+"";
                        pst=con.prepareStatement(sql);
                        pst.executeUpdate();
                        this.dispose();
                        Rest_password rest = new Rest_password();
                        rest.setVisible(true);
                    }else{
                        Toolkit.getDefaultToolkit().beep();
                        lbl_msg.setVisible(true);
                    }
                    
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btnconfrimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Confirm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnconfrim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_msg;
    private javax.swing.JTextField txtcode;
    // End of variables declaration//GEN-END:variables
}
