
package student_managment;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;



/**
 *
 * @author Sovuthyna
 */
public class Login_form extends javax.swing.JFrame {

    /**
     * Creates new form Login_form
     */
    public Login_form() {
        initComponents();
        SetIcons objs = new SetIcons();
        objs.SetIcons(this);
    }

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    String sql;
    int att;
    String user_level;
    
    Border borderCh = BorderFactory.createLineBorder(Color.RED, 1);
    Border borderRe = BorderFactory.createLineBorder(new Color(204,204,204), 1);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_forgot = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        txt_pass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        btn_login = new javax.swing.JButton();
        cbo_user_level = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        show_hide_pass = new javax.swing.JCheckBox();
        lbl_log_wrong = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jPanel2.setBackground(new java.awt.Color(216, 237, 224));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user_account_100px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("User Info");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Please complete your infomation, here");

        lbl_forgot.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_forgot.setForeground(new java.awt.Color(0, 51, 153));
        lbl_forgot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_forgot.setText("Forgot Password ?");
        lbl_forgot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_forgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_forgotMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel2))
                                    .addComponent(jLabel1)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lbl_forgot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_forgot, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Users Login");

        txt_user.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_user.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txt_user.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_userFocusLost(evt);
            }
        });

        txt_pass.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_pass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txt_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_passKeyReleased(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/password_32px.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user_32px.png"))); // NOI18N

        btn_exit.setBackground(new java.awt.Color(204, 204, 204));
        btn_exit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_exit.setText("Exit");
        btn_exit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_exitMouseExited(evt);
            }
        });
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        btn_login.setBackground(new java.awt.Color(204, 204, 204));
        btn_login.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_login.setText("Login");
        btn_login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_loginMouseExited(evt);
            }
        });
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        cbo_user_level.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbo_user_level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));
        cbo_user_level.setSelectedIndex(1);
        cbo_user_level.setToolTipText("");
        cbo_user_level.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        cbo_user_level.setFocusCycleRoot(true);
        cbo_user_level.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbo_user_levelKeyPressed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checked_user_male_32px.png"))); // NOI18N
        jLabel7.setText("1");

        show_hide_pass.setBackground(new java.awt.Color(255, 255, 255));
        show_hide_pass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        show_hide_pass.setForeground(new java.awt.Color(102, 102, 102));
        show_hide_pass.setText("Show password");
        show_hide_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_hide_passActionPerformed(evt);
            }
        });

        lbl_log_wrong.setForeground(new java.awt.Color(255, 255, 255));
        lbl_log_wrong.setText(".");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_user, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_pass, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbo_user_level, 0, 216, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_log_wrong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(show_hide_pass)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbo_user_level, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(show_hide_pass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_log_wrong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void show_hide_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_hide_passActionPerformed
        
        if (show_hide_pass.isSelected()){
            txt_pass.setEchoChar((char)0);
        }else{
            txt_pass.setEchoChar('\u25cf');
        }
    }//GEN-LAST:event_show_hide_passActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        //int opt=JOptionPane.showConfirmDialog(null, "Do you want to exit?", "Confirm", JOptionPane.YES_NO_OPTION);
       // if(opt == 0){
        //   this.dispose();
        System.exit(0);
        //} 
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        
        con=ConDB.getConnection();
            if (txt_user.getText().trim().equals("")){
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "Please input Username","Message",JOptionPane.WARNING_MESSAGE);
                txt_user.requestFocus();
                txt_user.setBorder(borderCh);
            }else if(txt_pass.getText().trim().equals("")){
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "Please input Password","Message",JOptionPane.WARNING_MESSAGE);
                txt_pass.requestFocus();
                txt_pass.setBorder(borderCh);
            }else{

                con=ConDB.getConnection();
                try {
                String sql_2="Select attempt_count, user_lavel From tbl_user Where username='"+txt_user.getText().trim()+"'";
                Statement stm;
                ResultSet rss;
                stm=con.createStatement();
                rss=stm.executeQuery(sql_2);
                    if(rss.next()){
                        att=rss.getInt("attempt_count");
                        user_level=rss.getString("user_lavel");
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                
                sql="SELECT username FROM tbl_user WHERE username='"+txt_user.getText().trim()+"'";
                try {
                pst=con.prepareStatement(sql);
                rs=pst.executeQuery();

                    if(rs.next()){
                        sql="SELECT password FROM tbl_user WHERE password='"+txt_pass.getText().trim()+"'"
                            +"AND username='"+txt_user.getText().trim()+"' ";
                        pst=con.prepareStatement(sql);
                        rs=pst.executeQuery();

                        if(rs.next()){

                            sql="SELECT user_lavel FROM tbl_user WHERE password='"+txt_pass.getText().trim()+"'"
                            +"AND username='"+txt_user.getText().trim()+"' AND user_lavel='"+cbo_user_level.getSelectedItem().toString()+"'";

                            pst=con.prepareStatement(sql);
                            rs=pst.executeQuery();

                            if(rs.next()){

                                sql="SELECT status FROM tbl_user WHERE password='"+txt_pass.getText().trim()+"'"
                                +"AND username='"+txt_user.getText().trim()+"' AND user_lavel='"+cbo_user_level.getSelectedItem().toString()+"'"
                                        + "AND status='Active'";

                                pst=con.prepareStatement(sql);
                                rs=pst.executeQuery();

                                if(rs.next()){

                                    sql="SELECT status FROM tbl_user WHERE password='"+txt_pass.getText().trim()+"'"
                                        +"AND username='"+txt_user.getText().trim()+"' AND user_lavel='"+cbo_user_level.getSelectedItem().toString()+"'"
                                                + "AND status='Active' AND attempt_count <= 3";

                                        pst=con.prepareStatement(sql);
                                        rs=pst.executeQuery();

                                        if(rs.next()){
                                            ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/img/ok_32px.png"));
                                            JOptionPane.showMessageDialog(null, "Login Success, Welcome << "+txt_user.getText().trim()+" >>","Message",JOptionPane.INFORMATION_MESSAGE,icon);
                                            pst.close();
                                            this.dispose();
                                            Main_form Mn = new Main_form();
                                            Mn.setVisible(true);
                                            Main_form.lbl_user.setText(txt_user.getText().trim()); //Transform User name
					    Main_form.lbl_user_level.setText(cbo_user_level.getSelectedItem().toString());
                                        }else{
//                                            Toolkit.getDefaultToolkit().beep();
//                                            JOptionPane.showMessageDialog(null, "Sorry, << "+txt_user.getText()+" >> your account is <De-active>, please contact to Admin","Message",JOptionPane.INFORMATION_MESSAGE);
//                                            txt_user.setText("");
//                                            txt_pass.setText("");
//                                            cbo_user_level.setEnabled(false);
//                                            txt_user.setEnabled(false);
//                                            txt_pass.setEnabled(false);
//                                            btn_login.setEnabled(false);
//                                            show_hide_pass.setEnabled(false);
                                        }

                                }else{
                                    Toolkit.getDefaultToolkit().beep(); //Block by stt
                                    JOptionPane.showMessageDialog(null, "Sorry, << "+txt_user.getText().trim()+" >> your account is Block, please contact to Admin","Message",JOptionPane.ERROR_MESSAGE);
                                    txt_user.setText("");
                                    txt_pass.setText("");
//                                    cbo_user_level.setEnabled(false);
//                                    txt_user.setEnabled(false);
//                                    txt_pass.setEnabled(false);
//                                    btn_login.setEnabled(false);
//                                    show_hide_pass.setEnabled(false);
                                }

                            }else{
                                Toolkit.getDefaultToolkit().beep();
                                JOptionPane.showMessageDialog(null, "Check your user level","Message",JOptionPane.INFORMATION_MESSAGE);
                            }

                        }else{
                            Toolkit.getDefaultToolkit().beep();
                            JOptionPane.showMessageDialog(null, "Incorect Password","Message",JOptionPane.ERROR_MESSAGE);
                            txt_pass.setText("");
                            txt_pass.requestFocus();
                            //////Block by att
                            try{
                                if(att < 3){
                                    //////////////////////if not Admin
                                        if(!user_level.equals("Admin")){
                                    //////////////////////
                                        att++;
                                        lbl_log_wrong.setText("Wrongs ("+att+") time");
                                        lbl_log_wrong.setForeground(Color.RED);
                                        String sql_1="Update tbl_user Set attempt_count='"+att+"' Where username='"+txt_user.getText().trim()+"'";
                                        Statement stm;
                                        stm=con.createStatement();
                                        stm.executeUpdate(sql_1);
                                        }
                                }else{
                                    Toolkit.getDefaultToolkit().beep();
                                    JOptionPane.showMessageDialog(null, "Sorry, << "+txt_user.getText().trim()+" >> your account is block, please contact to Admin","Message",JOptionPane.ERROR_MESSAGE);
                                    txt_user.setText("");
                                    txt_pass.setText("");
                                    cbo_user_level.setEnabled(false);
                                    txt_user.setEnabled(false);
                                    txt_pass.setEnabled(false);
                                    btn_login.setEnabled(false);
                                    show_hide_pass.setEnabled(false);
                                    
                                    ////Update Stt
                                    try {
                                        String sql_3="Update tbl_user Set status='No' Where username='"+txt_user.getText().trim()+"'";
                                        Statement stmt; stmt = con.createStatement();
                                        stmt.executeUpdate(sql_3);
                                        stmt.close();
                                    } catch (SQLException e) {
                                        JOptionPane.showMessageDialog(null, e);
                                    }
                                    
                                }
                            }catch(HeadlessException | SQLException e){
                                JOptionPane.showMessageDialog(null, e);
                            }

                        }

                    }else{
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(null, "Sorry, User << "+txt_user.getText().trim()+" >> is not avilable","Message",JOptionPane.WARNING_MESSAGE);
                    txt_user.setText("");
                    txt_user.requestFocus();
                }

                } catch (HeadlessException | SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            
            } 
        
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseEntered
        btn_login.setBackground(new Color(230, 230, 230));
    }//GEN-LAST:event_btn_loginMouseEntered

    private void btn_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseExited
        btn_login.setBackground(Color.white);
    }//GEN-LAST:event_btn_loginMouseExited

    private void btn_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseEntered
       btn_exit.setBackground(new Color(230, 230, 230));
    }//GEN-LAST:event_btn_exitMouseEntered

    private void btn_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseExited
       btn_exit.setBackground(Color.white);
    }//GEN-LAST:event_btn_exitMouseExited

    private void cbo_user_levelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbo_user_levelKeyPressed
        txt_user.requestFocus();
    }//GEN-LAST:event_cbo_user_levelKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Connection con;
        con=ConDB.getConnection();
    }//GEN-LAST:event_formWindowOpened

    private void txt_userFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_userFocusLost
        if(! txt_user.getText().equals("")){
            txt_user.setBorder(borderRe);
        }
    }//GEN-LAST:event_txt_userFocusLost

    private void txt_passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passKeyReleased
        txt_pass.setBorder(borderRe);
    }//GEN-LAST:event_txt_passKeyReleased

    private void lbl_forgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_forgotMouseClicked
        Forgot_Password fgp = new Forgot_Password();
        this.dispose();
        fgp.setVisible(true);
    }//GEN-LAST:event_lbl_forgotMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_form().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_login;
    private javax.swing.JComboBox<String> cbo_user_level;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_forgot;
    private javax.swing.JLabel lbl_log_wrong;
    private javax.swing.JCheckBox show_hide_pass;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
